config/routes.rb
Rails.application.routes.draw do

  root :to => 'users#index'
  resources :user_sessions
  resources :users

  get '/login' => 'user_sessions#new', :as => :login
  post '/logout' => 'user_sessions#destroy', :as => :logout
  get '/register' => 'users#new', :as => :register
  post '/create_session' => 'user_sessions#create', :as => :create_session

end

app/models/user.rb
class User < ActiveRecord::Base
  authenticates_with_sorcery!
  validates :name, presence: true, length: { maximum: 40 }
  validates :email, presence: true, format: { with: /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/i },
            uniqueness: { case_sensitive: false }
  validates :password, length: { minimum: 6 }, confirmation: true
  validates :password_confirmation, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_filter :require_login

  private
  def not_authenticated
    redirect_to login_path, alert: "You have to log in before continue."
  end
  include UserSessionsHelper
end

app/controllers/user_sessions_controller.rb
class UserSessionsController < ApplicationController
  skip_before_filter :require_login
  layout "empty_application"

  def new
    @user = User.new
  end

  def create
    if @user = login(params[:create_session][:email], params[:create_session][:password])
      remember_me!
      redirect_back_or_to(:users, notice: 'You successfully loged in')
    else
      flash.now[:alert] = 'Login failed'
      render action: 'new'
    end
  end

  def destroy
    forget_me!
    logout
    redirect_to login_url
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_filter :right_user, only: [:edit, :update]
  skip_before_filter :require_login, only: [:new, :create]

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
    render layout: "empty_application"
  end

  def create
    @user = User.new(user_params)
    if @user.save
      login(user_params[:email], user_params[:password])
      flash[:success] = "Welcome to the Task Manager."
      redirect_to @user
    else
      render 'new', layout: "empty_application"
    end
  end

  def edit
  end

  def update
    if @user.update_attributes(user_params)
      flash[:success] = "User successfully updated"
      redirect_to @user
    else
      render 'edit'
    end
  end

  def destroy
    User.find(params[:id]).destroy
    flash[:success] = "User deleted."
    redirect_to users_url
  end

  private
    def edit_user_params
      params.require(:user).permit(:email, :name)
    end
    def user_params
      params.require(:user).permit(:email, :name, :password, :password_confirmation)
    end
    def set_user
      @user = User.find(params[:id])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def set_title(title)
    site_name = 'Simple Task Manager'
    if title.empty?
      site_name
    else
      "#{title} - #{site_name}"
    end
  end
end

app/helpers/user_sessions_helper.rb
module UserSessionsHelper
  def current_user?(user)
    user == current_user
  end
  def right_user
      @user = User.find(params[:id])
      redirect_to(root_url) unless current_user?(@user)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_header.html.erb
<header class="navbar navbar-default">
  <div class="container">
    <%= link_to "Simple Task Manager", root_path, id: "logo", class: "navbar-brand" %>

    <ul class="nav navbar-nav">
      <li ><%= link_to "Registered Users", users_path %></li>
    </ul>

    <ul class="nav navbar-nav reg-menu" >
      <% if current_user %>
        <li><%= link_to "Edit Profile", edit_user_path(current_user.id) %></li>
        <li><%= link_to "Logout", :logout, method: :post %></li>
      <% else %>
         <li><%= link_to "Register", new_user_path %></li>
         <li><%= link_to "Login", :login %></li>
      <% end %>
    </ul>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TaskManager</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |key, value| %>
        <div class="alert alert-<%= key %>"><%= value %></div>
      <% end %>
      <%= yield %>
    </div>
  </body>
</html>
</html>

app/views/layouts/better_errors.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      <div class="glyphicon glyphicon-exclamation-sign">
      Form contains <%= pluralize(object.errors.count, "error") %>
      <ul>
        <% object.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  </div>
<% end %>

app/views/layouts/empty_application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= set_title(yield(:title)) %></title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="container">
    <%= yield %>
  </div>

</body>
</html>

app/views/user_sessions/_form.html.erb
    <%= form_for(:create_session, url: create_session_path) do |f| %>
      <div class="form-group">
        <%= f.text_field  :email,  class: "form-control", placeholder:"Email" %>
      </div>
      <div class="form-group">
        <%= f.password_field :password,  class: "form-control", placeholder: "Password" %>
      </div>
      <div class="form-group">
        <%= f.submit "Login", class: "btn btn-primary btn-lg btn-block" %>
      </div>
    <% end %>

app/views/user_sessions/new.html.erb
<div class="row">
  <div class="col-md-4"></div>
  <div class="col-md-4">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h3 class="panel-title">Log In</h3>
      </div>
      <div class="panel-body">
        <%= render 'form' %>
      </div>
    </div>
  </div>
  <div class="col-md-4"></div>
</div>




<!-- <a href="/register">register</a> -->

app/views/users/index.html.erb
<h2>All users</h2>

<ul class="users">
  <li></li>
</ul>

app/views/users/new.html.erb
<h2>Register</h2>
<%= form_for @user do |f| %>
  <%= render 'layouts/better_errors', object: f.object %>
  <div class="input-group">
    <%= f.text_field :email, class: "form-control", placeholder:"Email" %>
  </div>
  <div class="input-group">
    <%= f.text_field :name, class: "form-control", placeholder:"Name" %>
  </div>
  <div class="input-group">
    <%= f.password_field :password, class: "form-control", placeholder: "password" %>
  </div>
  <div class="input-group">
    <%= f.password_field :password_confirmation, class: "form-control", placeholder: "password confirm" %>
  </div>
  <div class="actions">
    <%= f.submit "Register", class: "btn btn-primary" %>
  </div>
<% end %>